/* ============================================================
   11_swords: CATÁLOGO MESTRE — 120 espadas (schema SwordItemSO)
   Tiers 1, 3 e 5: textos originais do GDD (src:'pdf').
   Tiers 2, 4 e 6: o PDF veio truncado -> criadas seguindo as
   regras de cada tier (src:'novo').
   Campos: swordID, swordName, tierLevel, baseDamage, attackSpeed,
   knockbackForce, critChance, projectilePrefab, attackType,
   passiveEffects[], OnSwing(combat, dir), OnHitEnemy(enemy, info)
   ============================================================ */
const SWORDS = [], SWORD_BY_NUM = {};
const LK = (sh, col, len, o) => Object.assign({ sh, col, len }, o || {});
const DEF_CRIT = { 1: .04, 2: .05, 3: .06, 4: .07, 5: .08, 6: .10 };
const TIER_STATION = { 1: 'anvil', 2: 'anvil', 3: 'advanvil', 4: 'advanvil', 5: 'forge', 6: 'forge' };
function S(num, name, d, v, k, look, fx, txt, rec, o) {
  o = o || {}; const t = Math.ceil(num / 20), id = 's' + String(num).padStart(3, '0');
  const sw = {
    swordID: num, num, id, swordName: name, tierLevel: t, baseDamage: d, attackSpeed: v, knockbackForce: k,
    critChance: o.crit !== undefined ? o.crit : DEF_CRIT[t], projectilePrefab: o.prefab || (fx.length ? 'Proj_' + id : null),
    attackType: o.atk || 'ArcSwing', passiveEffects: fx, look, txt, src: (t % 2 === 1) ? 'pdf' : 'novo', station: o.st || TIER_STATION[t],
    // métodos virtuais do SwordItemSO
    OnSwing(combat, dir) { const P = G.P; if (P && combat) fxCall(this, 'onSwing', P, combat, dir); },
    OnHitEnemy(enemy, info) { const P = G.P; if (P) fxCall(this, 'onHit', P, enemy, info.h || {}, info); },
  };
  sw.dps = d * v;
  fx.forEach(f => f.init && f.init(sw));
  const ing = {}; rec.split(',').forEach(p => { const [a, b] = p.split(':'); ing[a] = +b; });
  SWORDS.push(sw); SWORD_BY_NUM[num] = sw;
  IT[id] = { id, n: name, type: 'sword', tier: t, stack: 1, sw, ic: ['sword', sw], desc: txt };
  RECIPES.push({ out: id, n: 1, ing, st: sw.station });
  return sw;
}
// ======================= TIER 1 — INÍCIO DE JOGO & BÁSICO (001–020) [PDF] =======================
S(1, 'Madeira Reforçada', 8, 1.1, 4, LK('sword', '#a8763e', 30), [FX.kbLight(1.3)], 'Repulsão física aumentada em 30% contra inimigos terrestres leves.', 'wood:25,gel:4', { st: 'bench' });
S(2, 'Cobre Rúnico', 11, 1.3, 3, LK('sword', '#c8702d', 31, { glow: '#fde047' }), [FX.sparks()], 'Emite fagulhas elétricas de curtíssimo alcance (1 bloco) no ápice do arco.', 'copper_bar:8,gel:5', { st: 'bench' });
S(3, 'Ferro Forjado', 14, .9, 5, LK('broad', '#aeb4be', 33), [FX.frontBlock(.10)], 'Golpe pesado que bloqueia 10% do dano frontal durante a animação do ataque.', 'iron_bar:10');
S(4, 'Dente de Pedregulho', 16, .8, 6, LK('jagged', '#8b8f98', 30), [FX.groundShards(2, .3)], 'Cria 2 estilhaços de pedra no impacto que causam 30% do dano base no chão.', 'stone:80,iron_bar:6');
S(5, 'Vidro Vulcânico', 19, 1.5, 2, LK('jagged', '#2a2142', 31, { glow: '#a78bfa' }), [FX.bleed(2, 3), FX.breakChance(.05)], 'Aplica Sangramento Leve (2 dano/s por 3s). Espada possui 5% de chance de quebrar.', 'obsidian:12,iron_bar:4');
S(6, 'Agulha de Cacto', 12, 1.2, 3, LK('needle', '#3f9d4a', 32, { deco: 'spines' }), [FX.fanSpines(3, 36, 64)], 'Dispara 3 espinhos de cacto em leque curto com alcance de 4 blocos.', 'cactus:25,wood:5', { st: 'bench' });
S(7, 'Madeira Rúnica', 10, 1.4, 3, LK('sword', '#8a6a3a', 30, { glow: '#fde68a' }), [FX.runeLight()], 'Emite um pulso de luz fraca permanentemente que ilumina cavernas ao atacar.', 'wood:30,torch:5,gel:5', { st: 'bench' });
S(8, 'Cortadora de Espinhos', 15, 1.1, 4, LK('jagged', '#6a8a2a', 32), [FX.poisonSlow(.15, 4)], 'Envenena o alvo, reduzindo a velocidade de movimento do inimigo em 15%.', 'thorn:20,iron_bar:4');
S(9, 'Quartzo Polido', 13, 1.6, 2, LK('crystal', '#e5e7eb', 30, { glow: '#c7d2fe' }), [FX.comboSpeed(.05, .25)], 'Aumenta a velocidade de ataque consecutiva em +5% a cada acerto (máx +25%).', 'quartz:20,iron_bar:3');
S(10, 'Ouro Maciço', 18, 1.0, 4, LK('broad', '#f4c430', 33), [FX.goldBonus(.2)], 'Inimigos derrotados por esta espada dropam +20% de moedas de ouro.', 'gold_bar:10');
S(11, 'Prata Radiante', 17, 1.2, 4, LK('sword', '#dfe6ee', 34, { glow: '#ffffff' }), [FX.vsUndead(.5)], 'Causa +50% de dano bônus contra alvos do tipo Morto-Vivo (Zombies/Skeletons).', 'silver_bar:10');
S(12, 'Dente de Tubarão', 20, 1.3, 3, LK('fang', '#9db7c9', 34), [FX.submerged(1.0)], 'Aumenta o alcance da lâmina em +100% quando o jogador estiver submerso.', 'shark_tooth:12,iron_bar:4');
S(13, 'Lodo Verde Flutuante', 14, 1.0, 5, LK('gel', '#4ade80', 31, { glow: '#86efac' }), [FX.slowHit(.4, 1.5)], 'Aplica lentidão de 40% ao alvo por 1.5s através de gosma pegajosa.', 'gel:40,wood:6', { st: 'bench' });
S(14, 'Carvão Incandescente', 15, 1.1, 3, LK('sword', '#30303a', 31, { glow: '#ff7a1a' }), [FX.burnHit(3, 3)], 'Incendeia o alvo causando 3 de dano de fogo por segundo durante 3 segundos.', 'coal:25,iron_bar:3');
S(15, 'Âmbar Amarelo', 16, 1.2, 3, LK('crystal', '#ffb703', 30, { glow: '#ffd166' }), [FX.shieldHit(3, 15, 5)], 'Acertos concedem um mini-escudo temporário de 3 HP (acumula até 15 HP por 5s).', 'amber:15,iron_bar:4');
S(16, 'Clava de Osso Antigo', 22, .7, 7, LK('club', '#e8dfc6', 32), [FX.boneLob()], 'Arremessa um pequeno fragmento de osso em parábola no final do balanço.', 'bone:30,wood:10', { st: 'bench' });
S(17, 'Garra de Besouro', 15, 1.3, 4, LK('saber', '#4b6a3a', 30), [FX.armorPassive(3)], 'Concede +3 de armadura passiva para o jogador enquanto empunhada.', 'beetle_claw:12,iron_bar:3');
S(18, 'Cogumelo Azul', 13, 1.4, 2, LK('sword', '#38bdf8', 30, { glow: '#7dd3fc' }), [FX.staticSpores(3)], 'Solta esporos luminosos estáticos que causam dano a quem encostar.', 'glow_mushroom:15,wood:8', { st: 'bench' });
S(19, 'Bronzite Pesada', 21, .8, 8, LK('great', '#b0742f', 36), [], 'Possui o maior knockback do Tier 1, arremessando inimigos para longe.', 'bronzite_bar:12');
S(20, 'Pluma Leve', 12, 1.8, 1, LK('rapier', '#f5f5f4', 34), [FX.featherFall(.5)], 'Reduz a velocidade de queda do jogador em 50% enquanto estiver atacando no ar.', 'feather:15,iron_bar:3', { atk: 'Thrust' });
// ======================= TIER 2 — PRÉ-BOSSES INTERMEDIÁRIOS (021–040) [CRIADAS] =======================
S(21, 'Platina Cortante', 26, 1.3, 4, LK('sword', '#cfe3f1', 34, { glow: '#e0f2fe' }), [FX.shoot({ shape: 'blade', col: '#cfe3f1', col2: '#ffffff', glow: '#e0f2fe', r: 8, speed: 520, dm: .8, life: .22, pierce: 1 })], 'Dispara uma lâmina de platina reta e veloz com alcance de 7 blocos a cada golpe.', 'platinum_bar:10');
S(22, 'Presa Vampírica', 28, 1.2, 3, LK('fang', '#9f1239', 34), [FX.lifesteal(.03)], 'Roubo de vida baixo: cura 3% do dano causado (mínimo de 1 HP) a cada acerto.', 'vamp_tooth:12,iron_bar:6');
S(23, 'Ferrão de Vespa', 26, 1.5, 2, LK('rapier', '#e9b824', 36, { deco: 'spines' }), [FX.shoot({ n: 2, spreadDeg: 24, shape: 'needle', col: '#fde047', col2: '#ffffff', speed: 480, dm: .5, life: .5, r: 5, status: [['poison', 3, { dps: 3 }]], elem: 'poison' })], 'Dispara 2 ferrões retos em V que envenenam o alvo (3 de dano/s por 3s).', 'stinger:12,silver_bar:6', { atk: 'Thrust' });
S(24, 'Lâmina de Gelo Eterno', 30, 1.2, 4, LK('crystal', '#8bd3ff', 36, { glow: '#bae6fd' }), [FX.shoot({ shape: 'shard', col: '#a5f3fc', col2: '#ffffff', glow: '#7dd3fc', r: 8, speed: 500, dm: .9, life: .7, status: [['freeze', 2, { amt: .5 }]], elem: 'ice', sfx: 'ice' })], 'Dispara um estilhaço de gelo reto que congela o alvo (lentidão de 50% por 2s).', 'frost_shard:14,silver_bar:6');
S(25, 'Fornalha Viva', 34, 1.0, 5, LK('flame', '#ff6a2a', 36, { glow: '#fb923c' }), [FX.burnHit(4, 4), FX.embers()], 'Incendeia o alvo (4 de dano de fogo por segundo durante 4s) e deixa um rastro de brasas no ápice do arco.', 'hell_bar:10');
S(26, 'Martelo de Meteorito', 38, .8, 9, LK('club', '#6b4f4f', 38, { glow: '#ff9a52' }), [FX.massiveKB(2, .5)], 'Repulsão massiva: o knockback é dobrado e o alvo fica atordoado por 0.5s.', 'meteor_bar:16');
S(27, 'Gume de Rubi', 32, 1.2, 4, LK('saber', '#e11d48', 35, { glow: '#fb7185', gem: '#ef2e55' }), [FX.shoot({ shape: 'shard', col: '#ef2e55', col2: '#ffc0c8', glow: '#fb7185', r: 8, speed: 480, dm: .8, life: .8, heal: 2 })], 'Dispara um cristal de rubi reto que rouba 2 HP de vida a cada acerto.', 'ruby:12,gold_bar:6');
S(28, 'Esmeralda Peçonhenta', 29, 1.3, 3, LK('broad', '#10b981', 35, { glow: '#6ee7b7', gem: '#22d36f' }), [FX.shoot({ shape: 'shard', col: '#22d36f', col2: '#d1fae5', glow: '#34d399', r: 8, speed: 470, dm: .8, life: .8, status: [['poison', 4, { dps: 2, stack: 3 }]], elem: 'poison' })], 'Dispara uma esmeralda reta; cada acerto acumula veneno (até 3 cargas de 2 de dano/s).', 'emerald:12,gold_bar:6');
S(29, 'Topázio Trovejante', 31, 1.4, 3, LK('sword', '#fbbf24', 34, { glow: '#fde047', gem: '#ffc21a' }), [FX.shoot({ shape: 'bolt', col: '#fde047', col2: '#ffffff', glow: '#facc15', r: 7, speed: 620, dm: .8, life: .6, status: [['stun', .4]], elem: 'lightning' })], 'Dispara uma centelha reta que atordoa o alvo por 0.4s (choque).', 'topaz:12,platinum_bar:4');
S(30, 'Safira Glacial', 30, 1.3, 3, LK('gladius', '#2563eb', 33, { glow: '#60a5fa', gem: '#3b82f6' }), [FX.frostNova(54, .4)], 'Ao acertar, libera uma nova de gelo (raio de 3 blocos) que retarda inimigos próximos em 40%.', 'sapphire:12,frost_shard:6');
S(31, 'Titã de Pedra', 40, .7, 10, LK('great', '#7b8088', 40), [FX.massiveKB(1.4, 0), FX.wallSlam(.3)], 'Maior repulsão do Tier 2; inimigos arremessados contra blocos sofrem +30% de dano de colisão.', 'stone:80,obsidian:12,platinum_bar:6');
S(32, 'Cutelo do Carniceiro', 33, 1.1, 5, LK('cleaver', '#a11d1d', 35), [FX.bleed(4, 5), FX.lifesteal(.02)], 'Sangramento pesado (4 de dano/s por 5s) e roubo de vida baixo de 2%.', 'bone:25,vamp_tooth:6,platinum_bar:6');
S(33, 'Estilete dos Ventos', 27, 1.6, 1, LK('rapier', '#bde7d9', 36, { glow: '#d1fae5' }), [FX.shoot({ shape: 'blade', col: '#bde7d9', col2: '#ffffff', glow: '#a7f3d0', r: 8, speed: 660, dm: .7, life: .7, pierce: 2 })], 'Dispara uma lâmina de vento reta e veloz que atravessa 2 inimigos.', 'feather:12,platinum_bar:6,amethyst:4', { atk: 'Thrust' });
S(34, 'Magma Cristalizado', 36, .9, 6, LK('jagged', '#ff5a1f', 36, { glow: '#ff9a52' }), [FX.magmaDrop()], 'Arremessa uma gota de magma reta que explode em chamas (área pequena) ao colidir com inimigo ou bloco.', 'hell_bar:8,obsidian:12,coal:10');
S(35, 'Sabre do Corsário', 28, 1.4, 4, LK('saber', '#d6b46a', 35), [FX.shoot({ shape: 'ball', col: '#3a3a44', col2: '#9a9aa8', r: 7, speed: 560, dm: 1.5, life: .38, kbm: 1.2 })], 'Dispara uma bala de canhão curta que causa 150% do dano e empurra o alvo.', 'gold_bar:10,shark_tooth:8,wood:10');
S(36, 'Estocada Boreal', 31, 1.2, 6, LK('lance', '#9ad0ec', 44, { glow: '#bae6fd' }), [FX.shoot({ shape: 'shard', col: '#a5f3fc', col2: '#ffffff', glow: '#7dd3fc', r: 9, speed: 560, dm: .8, life: .5, pierce: 2, elem: 'ice', sfx: 'ice' }), FX.statusHit('freeze', 1, { amt: .6 }, 'melee')], 'Estocada que perfura até 2 inimigos em linha e congela o primeiro por 1s.', 'frost_shard:12,platinum_bar:6', { atk: 'Thrust' });
S(37, 'Lâmina do Crepúsculo', 35, 1.1, 4, LK('katana', '#4c1d95', 38, { glow: '#a78bfa' }), [FX.nightBonus(.2), FX.shoot({ shape: 'blade', col: '#6d28d9', col2: '#c4b5fd', glow: '#8b5cf6', r: 8, speed: 480, dm: .8, life: .8 })], 'Dispara um projétil de sombra reto; causa +20% de dano durante a noite.', 'platinum_bar:8,amethyst:10,bone:10');
S(38, 'Garra de Dragão Menor', 39, 1.0, 5, LK('saber', '#b91c1c', 37, { glow: '#f87171' }), [FX.shoot({ n: 3, spreadDeg: 30, shape: 'fire', r: 7, speed: 440, dm: .55, life: .6, status: [['burn', 3, { dps: 3 }]], elem: 'fire', glow: '#ff7a1a', glowR: 22, sfx: 'fire' })], 'Dispara 3 bolas de fogo retas em leque curto; queimam por 3 de dano/s durante 3s.', 'hell_bar:8,ruby:6,coal:12');
S(39, 'Dualidade Elemental', 37, 1.3, 4, LK('katana', '#f97316', 38, { glow: '#38bdf8' }), [FX.alternate(['burn', 3, { dps: 4 }, ['#ff7a1a', '#ffd23a']], ['freeze', 2, { amt: .5 }, ['#bae6fd', '#ffffff']])], 'Alterna os golpes: ímpares incendeiam o alvo, pares o congelam.', 'hell_bar:5,frost_shard:8,platinum_bar:4');
S(40, 'Fúria Estelar', 36, 1.1, 4, LK('broad', '#facc15', 35, { glow: '#fde047' }), [FX.starFall()], 'Invoca uma estrela cadente do céu em linha reta sobre o ponto do cursor.', 'meteor_bar:8,feather:12,topaz:6');
// ======================= TIER 3 — TRANSIÇÃO & MID-GAME (041–060) [PDF] =======================
S(41, 'Cortadora de Cobalto', 42, 1.4, 4, LK('sword', '#2f6fdb', 38, { glow: '#60a5fa' }), [FX.shoot({ shape: 'blade', col: '#3b82f6', col2: '#bfdbfe', glow: '#60a5fa', r: 10, speed: 760, dm: 1.0, life: .9, pierce: 4, kbm: .4, light: [.3, .5, 1], glowR: 30 })], 'Dispara um arco de plasma azul perfurante de rápida velocidade linear.', 'cobalt_bar:12,e_lightning:4');
S(42, 'Palladium Renovadora', 45, 1.2, 5, LK('broad', '#e8a864', 38, { glow: '#fda4af' }), [FX.regenAura(1, 5)], 'Concede a aura "Regeneração de Sangue", curando 1 HP/s durante 5s após acerto.', 'palladium_bar:12,e_blood:5');
S(43, 'Gládio de Mithril', 48, 1.6, 3, LK('gladius', '#5eead4', 36, { glow: '#99f6e4' }), [FX.burst(3)], 'Ataca em ráfagas ultra-rápidas de 3 golpes consecutivos em um único clique.', 'mithril_bar:12,e_water:4');
S(44, 'Orichalcum de Pétalas', 50, 1.3, 4, LK('saber', '#fb7185', 38, { glow: '#fecdd3' }), [FX.petals(5)], 'Invoca pétalas cortantes que voam das bordas da tela em direção ao alvo.', 'orichalcum_bar:12,e_earth:5');
S(45, 'Aço Noturno', 53, 1.1, 5, LK('katana', '#312e81', 40, { glow: '#818cf8' }), [FX.shadowEcho(.2)], 'Cria uma ilusão sombria atrás do jogador que repete o ataque 0.2s depois.', 'cobalt_bar:10,e_shadow:6');
S(46, 'Espírito Congelado', 46, 1.3, 4, LK('crystal', '#a5f3fc', 38, { glow: '#67e8f9' }), [FX.icicle()], 'Dispara uma estalactite de gelo que se divide em 3 fragmentos ao colidir.', 'cobalt_bar:8,e_ice:8');
S(47, 'Katana Eletrostática', 44, 1.7, 2, LK('katana', '#facc15', 40, { glow: '#fde047' }), [FX.chainShock()], 'Conecta alvos atingidos por uma corrente elétrica que causa dano compartilhado.', 'palladium_bar:10,e_lightning:8');
S(48, 'Foice do Pesadelo', 58, .8, 7, LK('scythe', '#4c1d95', 46, { glow: '#a855f7' }), [FX.spinBlade(3)], 'Lança uma lâmina sombria giratória que fica girando parada no ar por 3s.', 'mithril_bar:10,e_shadow:10');
S(49, 'Flora Selvagem', 49, 1.2, 4, LK('saber', '#16a34a', 38, { glow: '#86efac' }), [FX.vinesBelow()], 'Ergue espinhos de cipó do solo diretamente abaixo do inimigo atingido.', 'orichalcum_bar:8,e_poison:6,thorn:20');
S(50, 'Caos Ácido', 52, 1.0, 5, LK('jagged', '#84cc16', 38, { glow: '#bef264' }), [FX.corrodeHit()], 'Corrói a armadura do alvo, fazendo-o receber +25% de dano de todas as fontes.', 'palladium_bar:10,e_poison:8');
S(51, 'Cortadora Laser Antiga', 47, 1.5, 2, LK('rapier', '#f43f5e', 42, { glow: '#fda4af' }), [FX.laser(160)], 'Dispara feixe contínuo de luz instantânea reto de até 10 blocos de distância.', 'mithril_bar:10,e_light:6,e_lightning:4', { atk: 'Beam' });
S(52, 'Luz Sagrada', 51, 1.3, 4, LK('sword', '#fef9c3', 40, { glow: '#fde68a', gem: '#fbbf24' }), [FX.holyOrb()], 'Dispara uma esfera de luz que busca lentamente o inimigo mais próximo.', 'orichalcum_bar:10,e_light:8');
S(53, 'Dente de Kraken', 55, .9, 6, LK('fang', '#7c3aed', 40, { glow: '#c4b5fd' }), [FX.tentacle()], 'Gera um tentáculo do solo ao golpear que golpeia os alvos 2 vezes.', 'cobalt_bar:10,e_water:8,shark_tooth:6');
S(54, 'Lâmina Terrestre', 54, 1.1, 5, LK('broad', '#a16207', 40, { glow: '#fde68a' }), [FX.groundWaveApex({ hw: 11, hh: 13, speed: 320, life: .85, col: '#b4783a', col2: '#fde68a' })], 'Lança uma onda de choque pelo chão que segue a elevação dos blocos.', 'palladium_bar:12,e_earth:8');
S(55, 'Sabre de Fóton', 43, 2.0, 1, LK('rapier', '#e0f2fe', 42, { glow: '#7dd3fc' }), [FX.noCooldown()], 'Velocidade extrema de ataque contínuo sem cooldown ao manter o botão pressionado.', 'mithril_bar:12,e_light:8,e_lightning:6');
S(56, 'Espada do Sacrifício', 68, 1.0, 6, LK('great', '#7f1d1d', 44, { glow: '#ef4444' }), [FX.sacrifice(3, 1.0)], 'Drena 3 HP do jogador por golpe para causar +100% de dano massivo.', 'orichalcum_bar:12,e_blood:10');
S(57, 'Gládio de Mercúrio', 48, 1.4, 3, LK('gladius', '#cbd5e1', 36, { glow: '#f1f5f9' }), [FX.speedOnHit(2, 1.9)], 'Deixa o jogador ultra veloz por 2s após acertar um golpe em um inimigo.', 'palladium_bar:10,e_water:6,e_lightning:2');
S(58, 'Vulcão Ativo', 60, .8, 7, LK('great', '#44403c', 44, { glow: '#fb923c' }), [FX.eruption()], 'Cria uma erupção de lava no ponto de impacto lançando pedras em chamas.', 'orichalcum_bar:12,e_fire:10');
S(59, 'Cortadora Temporal', 50, 1.3, 3, LK('katana', '#fcd34d', 40, { glow: '#fef3c7' }), [FX.blink(3)], 'Teleporta o jogador 3 blocos para a frente instantaneamente no balanço.', 'mithril_bar:10,e_time:4');
S(60, 'Maldição Eterna', 56, 1.1, 5, LK('jagged', '#581c87', 42, { glow: '#c084fc' }), [FX.curseHit(10)], 'Impede que inimigos atingidos regenerem vida ou recebam buffs por 10s.', 'cobalt_bar:12,e_shadow:8,e_blood:4');
// ======================= TIER 4 — HARDMODE INICIAL (061–080) [CRIADAS] =======================
S(61, 'Abalo Sísmico', 80, 1.0, 7, LK('great', '#a16207', 46, { glow: '#fbbf24' }), [FX.groundWaveApex({ both: true, hw: 12, hh: 14, speed: 300, life: .64, col: '#b4783a', col2: '#fde68a' })], 'Onda de choque percorre o relevo do chão por 12 blocos em ambas as direções, acompanhando a elevação.', 'titanium_bar:10,e_earth:8');
S(62, 'Tremor do Colosso', 92, .8, 9, LK('great', '#78350f', 48, { glow: '#f59e0b' }), [FX.groundWaveApex({ waves: 2, gap: .12, hw: 20, hh: 22, speed: 280, life: .8, kbm: 1.3, kbDir: { x: 0, y: -1 }, col: '#92400e', col2: '#fde68a' })], 'Duas ondas de choque largas em sequência que arremessam os inimigos para o alto.', 'titanium_bar:14,e_earth:12');
S(63, 'Rachadura Tectônica', 84, .9, 7, LK('broad', '#7c2d12', 44, { glow: '#ff7a1a' }), [FX.fissure()], 'Abre uma fenda incandescente no chão que causa dano contínuo por 3s a quem a atravessar.', 'adamantite_bar:10,e_earth:8,e_fire:4');
S(64, 'Marreta da Montanha', 100, .75, 10, LK('club', '#57534e', 46, { glow: '#fbbf24' }), [FX.groundWaveApex({ both: true, hw: 12, hh: 14, speed: 280, life: .5, col: '#78716c', col2: '#e7e5e4' }), FX.stunGround(90, 1)], 'O impacto gera ondas de choque e atordoa por 1s os inimigos terrestres próximos.', 'adamantite_bar:16,e_earth:12');
S(65, 'Estalagmite Rúnica', 78, 1.0, 5, LK('sword', '#a8a29e', 42, { glow: '#fbbf24', gem: '#fbbf24' }), [FX.spikesAhead(3, 1.2, 26)], 'Ergue 3 estalagmites do chão à frente do jogador causando 120% do dano.', 'titanium_bar:8,e_earth:6,quartz:10');
S(66, 'Presa de Cristal', 82, 1.1, 5, LK('crystal', '#c084fc', 44, { glow: '#e9d5ff' }), [FX.crystalLine(6)], 'Uma linha de estalagmites de cristal irrompe do solo em cascata, na direção do alvo.', 'titanium_bar:8,e_earth:6,e_light:4');
S(67, 'Lança de Calcário', 88, .95, 6, LK('lance', '#d6d3d1', 50, { glow: '#fde68a' }), [FX.giantSpike()], 'Uma enorme estalagmite irrompe sob o inimigo atingido causando 200% do dano.', 'adamantite_bar:10,e_earth:10', { atk: 'Thrust' });
S(68, 'Coroa de Pedra', 90, .9, 7, LK('sword', '#78716c', 44, { glow: '#fde68a', gem: '#fbbf24' }), [FX.spikeRing(6)], 'Cerca o inimigo atingido com um anel de 6 estalagmites que o aprisionam e ferem.', 'titanium_bar:12,e_earth:10,e_shadow:4');
S(69, 'Esporo Fantasma', 74, 1.3, 3, LK('sword', '#c4b5fd', 42, { glow: '#a78bfa' }), [FX.orbitSpores(4)], 'Libera 4 esporos flutuantes que orbitam o jogador por 6s e explodem ao tocar inimigos.', 'titanium_bar:8,spore:20,e_poison:6', { atk: 'Orbital' });
S(70, 'Cogumelo Profano', 76, 1.2, 3, LK('club', '#65a30d', 42, { glow: '#84cc16' }), [FX.toxicCloud()], 'Cada acerto libera uma nuvem de esporos tóxicos flutuantes (dano contínuo por 4s).', 'adamantite_bar:8,spore:25,e_poison:8');
S(71, 'Colheita Micélica', 72, 1.4, 2, LK('saber', '#86efac', 42, { glow: '#4ade80' }), [FX.driftSpores(3, 2, false)], 'Esporos flutuantes curam o jogador em 2 HP quando atingem inimigos.', 'titanium_bar:8,spore:20,e_blood:6');
S(72, 'Fungo da Perdição', 86, 1.1, 4, LK('jagged', '#7e22ce', 44, { glow: '#a855f7' }), [FX.driftSpores(3, 0, true)], 'Esporos à deriva se atraem a inimigos próximos e causam lentidão de 45%.', 'adamantite_bar:9,spore:25,e_shadow:6');
S(73, 'Núcleo Gravitacional', 94, 1.0, 5, LK('great', '#4c1d95', 46, { glow: '#a78bfa' }), [FX.gravAura({ r: 110, life: 4, pull: 340, slow: .4, col: '#a78bfa' })], 'Cria uma aura gravitacional ao redor do jogador por 4s que puxa inimigos e reduz sua velocidade em 40%.', 'titanium_bar:10,e_time:6,e_light:4');
S(74, 'Pêndulo Orbital', 85, 1.2, 6, LK('gladius', '#1e3a8a', 40, { glow: '#60a5fa' }), [FX.gravAura({ r: 90, life: 3, pull: -380, push: true, killProj: true, col: '#60a5fa' })], 'Aura gravitacional repulsiva por 3s: afasta inimigos e desintegra projéteis hostis dentro de 5 blocos.', 'adamantite_bar:10,e_time:6,e_water:4');
S(75, 'Anomalia de Gravidade', 96, .95, 6, LK('crystal', '#0e7490', 44, { glow: '#67e8f9' }), [FX.antiGravHit(80, 2.2)], 'Inverte a gravidade dos inimigos atingidos numa área, fazendo-os flutuar por 2s.', 'titanium_bar:12,e_time:8');
S(76, 'Lente Gravitacional', 80, 1.1, 4, LK('crystal', '#be185d', 42, { glow: '#f9a8d4' }), [FX.gravAura({ r: 100, life: 4, slow: .6, mark: true, col: '#f9a8d4' })], 'Aura de lente: inimigos dentro dela sofrem +15% de dano e ficam 60% mais lentos.', 'adamantite_bar:12,e_light:8,e_time:4');
S(77, 'Titânio Vulcânico', 98, .9, 7, LK('great', '#d3dcf0', 46, { glow: '#fb923c' }), [FX.groundWaveApex({ hw: 12, hh: 14, speed: 320, life: .8, fire: true, col: '#ff7a1a', col2: '#fff2a0' }), FX.burnHit(8, 3)], 'Onda de choque flamejante no chão que deixa chamas por 3s e incendeia o alvo.', 'titanium_bar:12,e_fire:12,e_earth:6');
S(78, 'Adamantita Sísmica', 104, .8, 8, LK('great', '#e8203f', 48, { glow: '#fb7185' }), [FX.groundWaveApex({ waves: 3, gap: .18, hw: 12, hh: 16, speed: 300, life: .5, col: '#be123c', col2: '#fecdd3' })], 'Três ondas de choque consecutivas a cada golpe, cada uma indo mais longe que a anterior.', 'adamantite_bar:14,e_earth:14');
S(79, 'Estalactite Invertida', 83, 1.2, 4, LK('jagged', '#78716c', 42, { glow: '#fde68a' }), [FX.ceilingSpikes()], 'Estalagmites e estalactites brotam do chão e do teto ao redor do alvo atingido.', 'titanium_bar:10,e_ice:8,e_earth:6');
S(80, 'Eclipse Terrestre', 102, .85, 8, LK('great', '#312e81', 48, { glow: '#fbbf24' }), [FX.gravShock()], 'Combina onda de choque e aura gravitacional: puxa os inimigos ao ápice e os esmaga com ondas no chão.', 'adamantite_bar:16,e_earth:10,e_time:6');
// ======================= TIER 5 — HARDMODE AVANÇADO (081–100) [PDF] =======================
S(81, 'Destruidora Solar', 120, 1.2, 6, LK('great', '#f59e0b', 50, { glow: '#fde047', gem: '#ef4444' }), [FX.solarMeteor()], 'Invoca um meteoro solar massivo que destrói blocos e devasta a área.', 'celestial_bar:10,e_fire:15');
S(82, 'Lâmina Dimensional', 115, 1.4, 4, LK('katana', '#6d28d9', 50, { glow: '#c4b5fd' }), [FX.phaseBlade()], 'Ataque atravessa paredes, obstáculos e terrenos sem perder dano.', 'celestial_bar:9,e_shadow:12,e_time:4');
S(83, 'Matéria Escura', 130, 1.0, 7, LK('great', '#1e1b4b', 52, { glow: '#7c3aed' }), [FX.darkMatter()], 'Cria um mini buraco negro no impacto que suga todos os inimigos próximos.', 'celestial_bar:12,e_shadow:15');
S(84, 'Katana do Vazio', 110, 1.8, 3, LK('katana', '#1e293b', 52, { glow: '#818cf8' }), [FX.voidStep()], 'Concede 2s de Invisibilidade e Invulnerabilidade após eliminar um alvo.', 'celestial_bar:9,e_shadow:10,e_time:5');
S(85, 'Cortadora da Galáxia', 125, 1.3, 5, LK('saber', '#4338ca', 50, { glow: '#f472b6' }), [FX.galaxy()], 'Dispara uma espiral de 4 planetas orbitantes que expandem em leque.', 'celestial_bar:10,e_light:10,e_time:4', { atk: 'Orbital' });
S(86, 'Tempo Congelado', 118, 1.2, 5, LK('gladius', '#fcd34d', 46, { glow: '#fef3c7' }), [FX.timeStopCrit(1.5)], 'Para o tempo e a movimentação de todos os inimigos na tela por 1.5s no Crit.', 'celestial_bar:10,e_time:10', { crit: .35 });
S(87, 'Gládio Nebular', 122, 1.4, 4, LK('gladius', '#a21caf', 48, { glow: '#f0abfc' }), [FX.plasmaSeekers(2)], 'Invoca esferas de plasma auto-guiadas que perseguem alvos autonomamente.', 'celestial_bar:10,e_light:8,e_shadow:6');
S(88, 'Singularidade Denso', 135, .9, 8, LK('great', '#0f172a', 52, { glow: '#94a3b8' }), [FX.compressHit(6)], 'Comprime a massa dos inimigos reduzindo o tamanho e a defesa deles.', 'celestial_bar:12,e_earth:10,e_shadow:8');
S(89, 'Fim dos Tempos', 140, 1.1, 6, LK('scythe', '#7e22ce', 56, { glow: '#e879f9' }), [FX.cosmicRot()], 'Aplica Podridão Cósmica (100 de dano por segundo durante 4 segundos).', 'celestial_bar:12,e_time:10,e_blood:10');
S(90, 'Cortadora Hiperbólica', 112, 1.6, 3, LK('rapier', '#f87171', 50, { glow: '#fecaca' }), [FX.hyperReach(.2)], 'Aumenta o alcance físico da lâmina em +20% a cada golpe no ar.', 'celestial_bar:9,e_lightning:10', { atk: 'Thrust' });
S(91, 'Foice do Titã', 150, .8, 9, LK('scythe', '#78350f', 58, { glow: '#fbbf24' }), [FX.pctMaxHp(.05)], 'Causa dano proporcional à vida máxima do alvo (5% Max HP bônus).', 'celestial_bar:14,e_earth:15,e_blood:6');
S(92, 'Luz Pulsante Nova', 116, 1.5, 4, LK('crystal', '#fef9c3', 48, { glow: '#ffffff' }), [FX.flashBlind(3)], 'Emite um flash fotônico que cega todos os inimigos da tela por 3 segundos.', 'celestial_bar:10,e_light:12');
S(93, 'Sabre Corrosivo Solar', 128, 1.2, 5, LK('flame', '#f97316', 50, { glow: '#fde047' }), [FX.solarFlames(3)], 'Deixa chamas solares estáticas no ar que causam dano contínuo por 6s.', 'celestial_bar:11,e_fire:10,e_poison:6');
S(94, 'Caos Primordial', 121, 1.4, 4, LK('jagged', '#10b981', 50, { glow: '#f0abfc' }), [FX.chaosElem()], 'Aplica um efeito elemental aleatório diferente (Fogo/Gelo/Raio/Veneno) por golpe.', 'celestial_bar:10,e_fire:5,e_ice:5,e_lightning:5,e_poison:5');
S(95, 'Devoradora de Deuses', 145, 1.0, 7, LK('great', '#450a0a', 54, { glow: '#dc2626' }), [FX.lowHpFrenzy(.3, 1.0)], 'Concede +100% de velocidade de ataque se o HP do jogador estiver abaixo de 30%.', 'celestial_bar:13,e_blood:15');
S(96, 'Cortadora Quantum', 124, 1.5, 3, LK('katana', '#06b6d4', 50, { glow: '#a5f3fc' }), [FX.backstab(2.5)], 'O dano é multiplicado por 2.5x se o ataque for realizado pelas costas do alvo.', 'celestial_bar:10,e_shadow:8,e_time:6', { crit: .12 });
S(97, 'Rúnica Celestial', 132, 1.2, 5, LK('sword', '#fde68a', 52, { glow: '#fbbf24', gem: '#fbbf24' }), [FX.swordRain(6)], 'Invoca uma chuva vertical de espadas de luz que caem em linha reta.', 'celestial_bar:11,e_light:12');
S(98, 'Gládio Antimatéria', 138, 1.1, 6, LK('gladius', '#e0f2fe', 48, { glow: '#a5f3fc' }), [FX.antiProj()], 'Desintegra instantaneamente projéteis inimigos que tocarem na lâmina.', 'celestial_bar:11,e_light:8,e_shadow:8');
S(99, 'Pesadelo Profundo', 127, 1.3, 5, LK('saber', '#581c87', 50, { glow: '#e879f9' }), [FX.panicAura(150, 3)], 'Causa o efeito Pânico em área, fazendo inimigos fugirem do jogador por 3s.', 'celestial_bar:11,e_shadow:12');
S(100, 'Sabre do Julgamento', 142, 1.0, 7, LK('great', '#fff7c2', 56, { glow: '#fbbf24' }), [FX.judgmentBeam()], 'Dispara um feixe contínuo de energia divina que atravessa a tela inteira.', 'celestial_bar:13,e_light:15,e_time:4', { atk: 'Beam' });
// ======================= TIER 6 — END-GAME / MÍTICO (101–120) [CRIADAS] =======================
S(101, 'Rastro Estelar', 180, 1.4, 5, LK('sword', '#fde68a', 52, { glow: '#fbbf24', gem: '#4f46e5' }), [FX.homingVolley(5)], 'Dispara 5 projéteis estelares rastreadores que perseguem alvos automaticamente.', 'mythic_core:1,celestial_bar:8,e_time:6');
S(102, 'Colapso Estelar', 230, .9, 8, LK('great', '#92400e', 56, { glow: '#fde68a', gem: '#4f46e5' }), [FX.starCollapse()], 'Implode uma estrela no ponto de impacto: puxa todos os inimigos próximos e os esmaga numa explosão enorme.', 'mythic_core:1,celestial_bar:12,e_light:10,e_time:8');
S(103, 'Portal do Abismo', 205, 1.2, 5, LK('katana', '#4c1d95', 54, { glow: '#c084fc', gem: '#4f46e5' }), [FX.portalBlades()], 'Abre 2 portais ao lado do alvo que disparam lâminas rastreadoras a cada 0.3s por 3s.', 'mythic_core:1,celestial_bar:10,e_shadow:12,e_time:6');
S(104, 'Julgamento Final', 270, .8, 9, LK('great', '#fff7c2', 60, { glow: '#fbbf24', gem: '#4f46e5' }), [FX.fullScreen(5, 1.5)], 'A cada 5 golpes, causa dano a todos os inimigos visíveis na tela.', 'mythic_core:1,celestial_bar:14,e_light:15,e_time:8');
S(105, 'Eterno Retorno', 195, 1.3, 4, LK('saber', '#22d3ee', 52, { glow: '#a5f3fc' }), [FX.boomerang()], 'Arremessa uma lâmina rastreadora que volta ao jogador, atingindo duas vezes (ida e volta).', 'mythic_core:1,celestial_bar:9,e_water:10,e_time:6');
S(106, 'Oráculo Cósmico', 215, 1.1, 5, LK('crystal', '#e879f9', 54, { glow: '#f0abfc', gem: '#4f46e5' }), [FX.oracleMarks()], 'Marca os inimigos atingidos por 6s; lâminas rastreadoras atacam automaticamente os alvos marcados.', 'mythic_core:1,celestial_bar:10,e_light:10,e_shadow:8');
S(107, 'Fenda Dimensional', 225, 1.0, 6, LK('great', '#0e7490', 56, { glow: '#67e8f9', gem: '#4f46e5' }), [FX.portalBeam()], 'No ápice, abre um portal de ataque que dispara uma lâmina gigante perfurante (300% do dano).', 'mythic_core:1,celestial_bar:11,e_shadow:10,e_time:8');
S(108, 'Constelação Viva', 190, 1.5, 4, LK('rapier', '#1e1b4b', 56, { glow: '#fde68a', gem: '#fde68a' }), [FX.starSeeds()], 'Cada golpe planta uma estrela viva no alvo; as estrelas disparam raios rastreadores por 8s.', 'mythic_core:1,celestial_bar:9,e_light:10,e_time:6', { atk: 'Thrust' });
S(109, 'Aurora Eterna', 240, 1.0, 6, LK('flame', '#5eead4', 58, { glow: '#a78bfa' }), [FX.auroraSweep()], 'Feixe de aurora que varre toda a tela de um lado a outro (dano em linha em tela cheia).', 'mythic_core:1,celestial_bar:12,e_light:12,e_ice:10', { atk: 'Beam' });
S(110, 'Eclipse Total', 255, .9, 7, LK('great', '#18181b', 58, { glow: '#c4b5fd', gem: '#4f46e5' }), [FX.eclipse()], 'Escurece a tela e causa dano a todos os inimigos visíveis (55% do dano), deixando-os cegos por 3.5s.', 'mythic_core:1,celestial_bar:13,e_shadow:15,e_time:8');
S(111, 'Hipernova', 265, .85, 9, LK('great', '#fff7c2', 60, { glow: '#fb923c', gem: '#ef4444' }), [FX.supernova()], 'No ápice, uma supernova explode sobre o cursor: dano em área gigantesca com flash de tela cheia.', 'mythic_core:1,celestial_bar:14,e_fire:15,e_light:12');
S(112, 'Ceifador de Almas', 200, 1.3, 3, LK('scythe', '#4338ca', 60, { glow: '#a5b4fc' }), [FX.soulScythes(3)], 'Lâminas espectrais rastreadoras brotam de inimigos derrotados e perseguem outros alvos.', 'mythic_core:1,celestial_bar:10,e_blood:12,e_shadow:10');
S(113, 'Lâmina da Criação', 210, 1.2, 5, LK('sword', '#fcd34d', 54, { glow: '#ffffff', gem: '#4f46e5' }), [FX.orbitBlades(3)], 'Cria 3 cópias espectrais da espada que orbitam o jogador por 5s e golpeiam alvos próximos.', 'mythic_core:1,celestial_bar:11,e_light:12,e_time:6', { atk: 'Orbital' });
S(114, 'Furacão Astral', 185, 1.6, 4, LK('scythe', '#6366f1', 54, { glow: '#c7d2fe' }), [FX.spiralScythes(3)], 'Dispara 3 foices rastreadoras em espiral a cada golpe.', 'mythic_core:1,celestial_bar:9,e_lightning:12,e_time:6');
S(115, 'Rei do Apocalipse', 280, .8, 10, LK('great', '#7f1d1d', 60, { glow: '#ef4444', gem: '#fde047' }), [FX.apocalypse(8)], 'Colapso de meteoros: 8 meteoros caem do céu sobre a área alvo, causando explosões em cadeia.', 'mythic_core:1,celestial_bar:15,e_fire:15,e_blood:10');
S(116, 'Singularidade Eterna', 235, .95, 7, LK('great', '#0f0a1f', 58, { glow: '#7c3aed', gem: '#4f46e5' }), [FX.homingHole()], 'Cria um buraco negro rastreador que persegue inimigos por 6s, sugando e esmagando tudo.', 'mythic_core:1,celestial_bar:13,e_shadow:15,e_time:10');
S(117, 'Mestre dos Portais', 220, 1.15, 5, LK('katana', '#a21caf', 56, { glow: '#f0abfc', gem: '#4f46e5' }), [FX.portalBurst(6)], 'Abre um portal no cursor que dispara 6 lâminas rastreadoras em todas as direções, duas vezes.', 'mythic_core:1,celestial_bar:11,e_shadow:12,e_time:8');
S(118, 'Armagedom', 275, .8, 8, LK('great', '#9a3412', 60, { glow: '#fb923c', gem: '#fde047' }), [FX.fullScreen(1, .35, { col: '#fb923c', label: 'ARMAGEDOM' })], 'Danos em tela cheia contínuos: todos os inimigos visíveis sofrem 35% do dano a cada golpe.', 'mythic_core:1,celestial_bar:14,e_fire:12,e_blood:10');
S(119, 'Origem do Cosmos', 250, 1.0, 6, LK('sword', '#312e81', 58, { glow: '#fde68a', gem: '#fde68a' }), [FX.cosmosOrigin()], 'Combina tudo: leque de 8 projéteis rastreadores e um portal de ataque que dispara uma lâmina gigante.', 'mythic_core:1,celestial_bar:13,e_light:12,e_time:12');
S(120, 'Gênesis Primordial', 280, 1.1, 8, LK('great', '#fff7c2', 62, { glow: '#fbbf24', gem: '#4f46e5' }), [FX.homingVolley(3, { dm: .5 }), FX.starCollapse('crit'), FX.fullScreen(3, .5, { label: 'GÊNESE', col: '#fde68a' })], 'A espada suprema: rastreadores a cada golpe, colapso estelar em críticos e dano em tela cheia a cada 3 golpes.', 'mythic_core:1,celestial_bar:20,e_light:15,e_time:15,e_shadow:12', { crit: .18 });
